# -*- coding: utf-8 -*-
"""Youtube_transcription

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uX20ztfzL5nH_50ckQq8V4oMRpPhYuj9
"""
!pip install youtube-transcript-api

from youtube_transcript_api import YouTubeTranscriptApi

def get_video_id(url):
    """
    Extracts the video ID from a YouTube URL.
    """
    if 'youtube.com' in url:
        return url.split('v=')[1].split('&')[0]
    elif 'youtu.be' in url:
        return url.split('/')[-1]
    else:
        raise ValueError("Invalid YouTube URL")

def fetch_transcript(video_id):
    """
    Fetches the transcript of a YouTube video given its video ID.
    """
    transcript = YouTubeTranscriptApi.get_transcript(video_id)
    return transcript

def format_transcript(transcript, interval=80):
    """
    Formats the transcript into readable paragraphs with timestamps in minutes.
    """
    formatted_text = ""
    current_paragraph = ""
    current_time = 0

    for entry in transcript:
        if current_time == 0:
            current_time = entry['start']

        if entry['start'] - current_time < interval:
            current_paragraph += " " + entry['text']
        else:
            minutes = int(current_time // 60)
            seconds = int(current_time % 60)
            formatted_text += f"[{minutes}:{seconds:02d}] " + current_paragraph.strip() + "\n\n"
            current_paragraph = entry['text']
            current_time = entry['start']

    # Append last paragraph
    if current_paragraph:
        minutes = int(current_time // 60)
        seconds = int(current_time % 60)
        formatted_text += f"[{minutes}:{seconds:02d}] " + current_paragraph.strip()

    return formatted_text

def main(url):
    try:
        video_id = get_video_id(url)
        transcript = fetch_transcript(video_id)
        formatted_transcript = format_transcript(transcript)
        print(formatted_transcript)
    except Exception as e:
        print(f"Error: {e}")

# Example usage
url = "https://www.youtube.com/watch?v=NL2CiARkf7M"  # Replace this with the YouTube URL
main(url)
